### ISSUE TITLE
Duplicate targets

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-cmake#32]
This is a cross-repo issue, but I post it here since it involves the build system.

I just recently got the following message from cmake in dune-cornerpoint:
```
CMake Error at CMakeLists.txt:112 (add_custom_target):
  add_custom_target cannot create target "check-commits" because another
  target with the same name already exists.  The existing target is a custom
  target created in source directory
  "/Users/atgeirr/opm-build-debug/dune-cornerpoint".  See documentation for
  policy CMP0002 for more details.
```
Apparently, this target is added both by opm-cmake/cmake/OpmLibMain.cmake and the CMakeLists.txt of some of the modules. I guess that it should be removed from the module-specific files? At least that appears to work for dune-cornerpoint, but I wanted to hear from the cmake experts if this is indeed the correct fix. (Also, a mystery: why did I not experience this before, the conflict has been there since May 28?)

**Comment by akva2** [comment]
strange, see https://github.com/OPM/dune-cornerpoint/commit/e1364d955cdc3b02e49ec821d6866292d11d19e4

should have been done across all modules. make sure you are up to date.

**Comment by atgeirr** [comment]
Sorry for messing up this, I re-cloned and failed to update from upstream.
